// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_movies_id_ from "./routes/api/movies/[id].ts";
import * as $api_movies_index from "./routes/api/movies/index.ts";
import * as $api_movies_types_d from "./routes/api/movies/types.d.ts";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/movies/[id].ts": $api_movies_id_,
    "./routes/api/movies/index.ts": $api_movies_index,
    "./routes/api/movies/types.d.ts": $api_movies_types_d,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
